### ISSUE TITLE
I encountered an error when training the model with the Kitti dataset.

### ISSUE THREAD

**Issue by 2000lf** [XuyangBai/TransFusion#104]
` File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'KittiDataset is not in the dataset registry'
`

**Comment by 2000lf** [comment]
`Traceback (most recent call last):
  File "tools/train.py", line 255, in <module>
    main()
  File "tools/train.py", line 244, in main
    train_detector(
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/apis/train.py", line 223, in train_detector
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'KittiDataset is not in the dataset registry'
`

**Comment by 2000lf** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 255, in <module>
    main()
  File "tools/train.py", line 244, in main
    train_detector(
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/apis/train.py", line 223, in train_detector
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/shiying/zjx/envs/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'KittiDataset is not in the dataset registry'
