### ISSUE TITLE
undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [XuyangBai/TransFusion#44]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I have the following installations and try to run the following installations but ending up with the below error

torch - 1.12.0
torchvision - 0.13.0
mmdet - 2.25.0
mmdet3d - 0.11.0
 
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_detector, show_result_meshlab
  File "/home/hykeserver/Downloads/3d_OD/TransFusion-master/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector, init_detector,
  File "/home/hykeserver/Downloads/3d_OD/TransFusion-master/mmdet3d/apis/inference.py", line 8, in <module>
    from mmdet3d.core import Box3DMode, show_result
  File "/home/hykeserver/Downloads/3d_OD/TransFusion-master/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/hykeserver/Downloads/3d_OD/TransFusion-master/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ImportError: /home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l**

**Reproduction**
1. What command or script did you run?
```
python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
nuScenes
**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
Getting the below error while running the above command
**Traceback (most recent call last):
  File "mmdet3d/utils/collect_env.py", line 18, in <module>
    for name, val in collect_env().items():
  File "mmdet3d/utils/collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/utils/env.py", line 87, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/hykeserver/anaconda3/envs/transfusion/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l**
3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by carry-all-coder** [comment]
Same issue! Have you found out how to sovle it?
